### ISSUE TITLE
This is wonderful,if has GUI 

### ISSUE THREAD

**Issue by ifrontend-xyz** [vasanthv/jsonbox#13]
This is wonderful,if has GUI

**Comment by vasanthv** [comment]
@ifrontend-xyz GUI for browsing the data?

**Comment by JacobRReed** [comment]
@ifrontend-xyz are you asking for a GUI to present you the url, or a GUI that can see and prettify json data?

**Comment by romarioj2h** [comment]
I think that it will be good if it has a client to manipulate the data.

**Comment by JacobRReed** [comment]
@romarioj2h Do you mean something like Postman? Where you can send POST/GET to the url provided by jsonbox?
Or do you mean something where you get the url from jsonbox, then have a JSON editor built in where you can send POSTs and it will update with GET?

**Comment by JacobRReed** [comment]
@vasanthv @romarioj2h if you can specify i can try to work on a gui for it, just not sure what you are looking for

**Comment by ifrontend-xyz** [comment]
1.one page for query data use id.
2.one page for store json data and auto create  api.

**Comment by vasanthv** [comment]
@ifrontend-xyz Don't you think a postman collection would do for it?

**Comment by JacobRReed** [comment]
ya although i like the challenge this is already a thing you can do with Postman

**Comment by ifrontend-xyz** [comment]
@vasanthv I need simple and stupid tool, not postman

**Comment by vasanthv** [comment]
@JacobRReed you up for it? you can also check out postwoman.io.

**Comment by jsejcksn** [comment]
@ifrontend-xyz Also check out https://insomnia.rest/

**Comment by ifrontend-xyz** [comment]
@jsejcksn thank you
