### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by hermanzdosilovic** [vasanthv/jsonbox#16]
Hi @vasanthv,

thank you for this awesome service!

Do you plan to create Docker image and instructions on how to self-deploy jsonbox?

Best regards,
Herman

**Comment by vasanthv** [comment]
@hermanzdosilovic No I don't have plan for that. But I am open to contributions on that front.

**Comment by hermanzdosilovic** [comment]
I can create a pull request with Dockerfile but I need instructions on how to build and run jsonbox locally
