### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by caique39** [vasanthv/jsonbox#32]
You are using the README as documentation, so I think that translations could be very helpful. What do you think about it?

**Comment by leonardiwagner** [comment]
Considering there's no documentation platform actually (to switch between languages), I think there's no reason to perform such translation right now.

The prior issue should be to create a documentation platform. A cheap solution could be using the [Wiki](https://guides.github.com/features/wikis/) though :+1: .

**Comment by caique39** [comment]
It makes perfect sense. Thanks!

**Comment by leonardiwagner** [comment]
@caique39 you could re-open this issue, just change the title name.

If you are really willing to translate and help, I think you can:
- Ask for the owner if you can perform the translation in markdown and attach to this project Wiki.
- Ask for the owner if you can do an HTML version of both English and Portuguese documentation to attach to the website.
