### ISSUE TITLE
Wrapper for Java / JVM

### ISSUE THREAD

**Issue by leonardiwagner** [vasanthv/jsonbox#33]
Hi, first of all, thanks for this amazing project! I've been using for a while then I decided to publish a Java wrapper version I've been using since there's no JVM wrapper yet.

The source-code and documentation is already [done](https://github.com/leonardiwagner/jsonbox).

However, unhappily Java world isn't that easy to publish a library :stuck_out_tongue_closed_eyes: , we have to open and ticket to request, so I did: https://issues.sonatype.org/browse/OSSRH-52070

But[ they are requesting to publish a text file in your domain](https://issues.sonatype.org/browse/OSSRH-52070?focusedCommentId=831477&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-831477) to use the "jsonbox" name on the library, such as https://jsonbox.io/javalib.txt with the ticket ID to be able to use that name

> Add a TXT record to your DNS referencing this JIRA ticket: OSSRH-52070

So I'd like to ask you that favor to be able to publish this library as  "jsonbox" on Java, otherwise the name would be "com.github.leonardiwagner.jsonbox" ...yes, a horribly horrible name :jack_o_lantern: 

If you consider that when I got the approval to publish I update you to remove that .txt file from your domain, and I create the pull request to add this library in README.md

thanks! :+1:

**Comment by leonardiwagner** [comment]
Second, do you have any interest in creating a "jsonbox" organization on GitHub? So we could transfer these wrapper repositories into the organization as well.. the contributing engagement, on these wrappers at least, could be higher.

**Comment by vasanthv** [comment]
@leonardiwagner sure, we can do that. Is it .txt file or TXT record or both?

**Comment by vasanthv** [comment]
@leonardiwagner added a TXT record in the DNS panel. Let me know once they verified it. Thanks a lot for the contribution.

**Comment by leonardiwagner** [comment]
@vasanthv a `.txt` file containing `OSSRH-52070` to be accessible via URL (eg.: https://jsonbox.io/textfile.txt)

I didn't get what "TXT Record" means

**Comment by vasanthv** [comment]
The issue says `Add a TXT record to your DNS referencing this JIRA ticket: OSSRH-52070 (Fastest)`. It's a DNS record to be added in the DNS control panel. I have added it and I think it should be enough. You can verify it here https://dnslookup.online/txt.html by giving the domain name.

**Comment by leonardiwagner** [comment]
@vasanthv it's done! You can remove the TXT record from your DNS, thank you!
