### ISSUE TITLE
Boxes are Down

### ISSUE THREAD

**Issue by searchy2** [vasanthv/jsonbox#43]
Can you please check that the hosted service is active?
I can't access any of my boxes. Thanks!

![MaxthonSnap20191115124821](https://user-images.githubusercontent.com/19896174/68967632-4150c780-07a6-11ea-8f88-2c94c4f73ca3.png)

**Comment by coffeeboo** [comment]
Same issue for me.

**Comment by vasanthv** [comment]
@searchy2 @coffeeboo The service is up now. Will investigate on why it down.

**Comment by vasanthv** [comment]
Looks like MongoDB Cloud Atlas has went down, that caused the service to go down. Need to add a recovery mechanism when the service it back. Thanks for reporting it.`
