### ISSUE TITLE
Rename "private boxes" to "protected boxes"

### ISSUE THREAD

**Issue by jsejcksn** [vasanthv/jsonbox#50]
This is an idea to improve the messaging/documentation.

The description of "private" boxes might be misleading to some because they can be _read_ without the API key. "Protected" might be a better description because only mutation actions (create/update/delete) require an API key.

**Comment by vasanthv** [comment]
Yeah, you are right `protected` is much better word for this. We can change that.

**Comment by jsejcksn** [comment]
@vasanthv I still see "private" in the repo description:

<img width="530" alt="jsonbox-private" src="https://user-images.githubusercontent.com/868251/77024285-206acf80-695c-11ea-8c93-aac22a100a79.png">

**Comment by vasanthv** [comment]
Fixed it. Thanks for pointing it out.
