### ISSUE TITLE
how long will the data be keeped?

### ISSUE THREAD

**Issue by jwenjian** [vasanthv/jsonbox#6]
as the title said, I'm wondering how long will the data be keeped? 1 month? forever?
and also, any other limitations that not mentioned on the README?

**Comment by vasanthv** [comment]
Your data wont be deleted until deleted by you. But if the APIs are abused then we might need to clear the data for that specific box.

**Comment by qgustavor** [comment]
I hope you can continue for a long time, although from my experience people abuse free services a lot (well, my most stared repo had this problem). If it gets hard to maintain I don't think you need to make it paid again, just add some kind of authentication.
