### ISSUE TITLE
[discussion] Remove the old unused data.

### ISSUE THREAD

**Issue by vasanthv** [vasanthv/jsonbox#62]
The current number of records in Jsonbox is `218058` and its keep growing. I know this day will come that we might need to cut down the records. So I have plan for that and I need suggestions from people to find the best possible way to cut down the number of records, so that people can keep use it for free.

**My suggestion:** 
Introduce `lastAccessedDate` for boxes (could be GET, POST or PUT). So when this date is more than 6 months (could be 3 months also) we delete them.

**Comment by harlev** [comment]
If you want to be careful, you could first just add the `lastAccessedDate` field. Then wait a while to see what are the usage patterns. If, for example, many records are written and then never accessed again, it would be an easy decision to delete those after 3 montha

**Comment by vasanthv** [comment]
> If you want to be careful, you could first just add the `lastAccessedDate` field. Then wait a while to see what are the usage patterns. If, for example, many records are written and then never accessed again, it would be an easy decision to delete those after 3 months

Yes I perfectly agree and thats the way I want to proceed.

**Comment by bvenkysubbu** [comment]
1. Many may use this service for quick testing and hence the data might only be required temporarily. My suggestion would be to have a default auto-delete in 48 hours feature, which can be disabled if the user wants it for more than 2 days.
2. Every time, a user opens https://jsonbox.io/, a box is created. That means a box is created even when a casual visitor comes to check the website out. This can be avoided by having a "create json box" button.
3. Many boxes may have empty data - e.g. https://jsonbox.io/box_d3b20d9deba976587eee. These can be deleted as well.

**Comment by vasanthv** [comment]
@bvenkysubbu thanks for your reply.

-  I like the idea of auto-delete. But 48 hours seems too little time. 
- There is no box creation step in jsonbox. We just show a random generated id each time the user visits.
- Also, the box will be created only when you first push your data to a box, so there is no concept of empty boxes as well.

**Comment by siair** [comment]
I am in favor of deleting it when the update date exceeds 6 or 3 months, rather than one month. One month seems a bit short..
