### ISSUE TITLE
suggestion: Make README into Github Pages?

### ISSUE THREAD

**Issue by cktang88** [vasanthv/jsonbox#64]
So that the "read the docs" link on https://jsonbox.io/ can point to the github page, which is easier to read.

**Comment by vasanthv** [comment]
@cktang88 I already have vasanthv.com pointing to https://github.com/vasanthv/vasanthv.github.io

So if I try to create a github page for this repo, it points to https://vasanthv.com/jsonbox by default. Is there any way to point this repo to docs.jsonbox.com? Or do I need to create a separate organisation for this?  But, I really don't like the idea of creating an organisation for this purpose. Any thoughts are welcome. :)
