### ISSUE TITLE
[feature request] allow IP whitelisting to access self hosted jsonbox

### ISSUE THREAD

**Issue by aakashlpin** [vasanthv/jsonbox#69]
Hey Vasanth,

Great work with jsonbox. Would you be open to the idea of having a config variable that allows for whitelisting an array of IP addresses for accessing self hosted jsonbox?

This would allow for the service to reside on a public IP address but be accessible only via VMs like on on DigitalOcean, or my local IP address etc. Would also make for quick way to spin up a private DB in the cloud where no stranger can simply create a record on my jsonbox. 

Happy to raise a PR for this one if you'd like.

**Comment by vasanthv** [comment]
I like the idea, feel free to raise PR. I would make the `*` or `0.0.0.0/0` be the default.

**Comment by harlev** [comment]
created #74 to address this request
