### ISSUE TITLE
Is it possible not to use Cloudflare?

### ISSUE THREAD

**Issue by siair** [vasanthv/jsonbox#72]
Today I received feedback that when connecting to jsonbox, someone encountered Cloudflare man-machine verification and  cause program error. Is it possible not to use Cloudflare? Otherwise, once the man-machine verification occurs, it will cause the data acquisition failure. This is very bad! Thanks.

**Comment by vasanthv** [comment]
Cloudflare is part of the current infrastructure. We are not planning to remove that in the near future. 
Feel free to spin up your own server.
