### ISSUE TITLE
Max Records in box 20

### ISSUE THREAD

**Issue by christianpappenberger** [vasanthv/jsonbox#77]
Hello guys,
I am experiencing a weird behavior. Whenever I am putting more than 20 records into a box the oldest one is removed so that the max records is never above 20 entries. Has somebody the same problem?
Chris

**Comment by vasanthv** [comment]
@christianpappenberger Hi, `get` method is paginated. 
The default limit is 20, you can define a limit. 
Try this like: https://jsonbox.io/box_36abd34548a4d6c91dae which returns just the first 20 records in the box.
I can get more records by setting limit param: https://jsonbox.io/box_36abd34548a4d6c91dae?limit=30

This is documented here: https://github.com/vasanthv/jsonbox#read
