### ISSUE TITLE
Make url on homepage relative

### ISSUE THREAD

**Issue by milovanderlinden** [vasanthv/jsonbox#8]
The url on the homepage is hardcoded in index.html but this should be determined based upon the host, f.i. when running on localhost

![image](https://user-images.githubusercontent.com/106038/65147295-1e13d100-da1e-11e9-9afa-5754ad8de00b.png)

**Comment by vasanthv** [comment]
Fixed. https://github.com/vasanthv/jsonbox/commit/98e8a56b270258f83eeeed831010e48cd60a939b
